### PR TITLE
Basic Merkle Tree 

### PR DESCRIPTION
**Pull request by TheRealBluesun**
## Abstract

This PR provides a basic merkle tree module with a SHA256 unit test.  This is a precursor to building a merkle tree for a contract's current state.

## Missing Features

Walking the tree, and providing proofs.

## Misc Notes

So much cleaner than the other embarrassment...

### CODE REVIEW

**Comment by hlb8122** [comment]
If you're happy with blake3 we can go in and replace the digest crate with https://crates.io/crates/blake3 and the Digest trait with https://docs.rs/blake3/0.3.2/blake3/struct.Hash.html

**Comment by TheRealBluesun** [comment]
It looks like `blake` [has an implementation](https://docs.rs/blake3/0.3.2/blake3/traits/index.html) for `Digest` as well, which seems to be shared by most other common hash libraries.  I am still planning on using `blake` generally, but I'd like to keep core pieces like this generic across some trait (be it `Digest` or whatever may be better).  

I'll see about making a unit test with `blake` to prove that it can be done without too much pain, and keep with the `Digest` trait if you're OK with that.

**Comment by hlb8122** [comment]
Ah yeah, https://docs.rs/blake3/0.3.2/src/blake3/traits.rs.html#18 `Input` and `FixedOutput` causes impl of `Digest`, missed that!

**Comment by TheRealBluesun** [comment]
I also updated the `rust-wasm` dependency to `master`, since I pulled in the contract interop stuff earlier today 😀

**Pull request merged**
